baseURL = "https://spanner-hacks.apstn.dev/"
languageCode = "ja-jp"
title = "Cloud Spanner Unofficial Hacks"
theme = "docsy"
enableGitInfo = true

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
github_repo = "https://github.com/apstndb/spanner-hacks"
