baseURL = "http://example.com/"
languageCode = "ja-jp"
title = "Cloud Spanner Unofficial Hacks"
theme = "docsy"
github_repo = "https://github.com/apstndb/spanner-hacks"

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
